AND GATE

In [4]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for AND GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.897256
iteration=  1000 cost=  0.546384
iteration=  2000 cost=  0.402756
iteration=  3000 cost=  0.323938
iteration=  4000 cost=  0.273867
iteration=  5000 cost=  0.238555
iteration=  6000 cost=  0.211888
iteration=  7000 cost=  0.190819
iteration=  8000 cost=  0.173647
iteration=  9000 cost=  0.159329
iteration=  10000 cost=  0.147183
iteration=  11000 cost=  0.136736
iteration=  12000 cost=  0.127648
Validating output for AND GATE
[[ 0.00581007]
 [ 0.13434431]
 [ 0.13643627]
 [ 0.8075307 ]]


OR GATE

In [11]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for OR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  1.97413
iteration=  1000 cost=  0.517401
iteration=  2000 cost=  0.374723
iteration=  3000 cost=  0.28777
iteration=  4000 cost=  0.231408
iteration=  5000 cost=  0.192529
iteration=  6000 cost=  0.164256
iteration=  7000 cost=  0.142842
iteration=  8000 cost=  0.126106
iteration=  9000 cost=  0.112698
iteration=  10000 cost=  0.101735
iteration=  11000 cost=  0.0926197
iteration=  12000 cost=  0.0849324
Validating output for OR GATE
[[ 0.17748648]
 [ 0.93196607]
 [ 0.92991161]
 [ 0.99881411]]


NOT GATE

In [25]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,1])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([1,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0],[1]])
op=np.array([[1],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for NOT GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  1.55883
iteration=  1000 cost=  0.492868
iteration=  2000 cost=  0.294683
iteration=  3000 cost=  0.20192
iteration=  4000 cost=  0.150958
iteration=  5000 cost=  0.119531
iteration=  6000 cost=  0.0984808
iteration=  7000 cost=  0.0835042
iteration=  8000 cost=  0.0723536
iteration=  9000 cost=  0.063754
iteration=  10000 cost=  0.0569334
iteration=  11000 cost=  0.0513995
iteration=  12000 cost=  0.0468245
Validating output for NOT GATE
[[ 0.94507837]
 [ 0.03647145]]


EXOR

In [26]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)

cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)

optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[0]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for EXOR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  0.999027
iteration=  1000 cost=  0.697775
iteration=  2000 cost=  0.695169
iteration=  3000 cost=  0.694067
iteration=  4000 cost=  0.693566
iteration=  5000 cost=  0.693338
iteration=  6000 cost=  0.693234
iteration=  7000 cost=  0.693187
iteration=  8000 cost=  0.693165
iteration=  9000 cost=  0.693155
iteration=  10000 cost=  0.693151
iteration=  11000 cost=  0.693149
iteration=  12000 cost=  0.693148
Validating output for EXOR GATE
[[ 0.5010137 ]
 [ 0.50014871]
 [ 0.50016946]
 [ 0.49930444]]


EXNOR

In [27]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)

cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)

optimizer = tf.train.GradientDescentOptimizer(0.05).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[1],[0],[0],[1]])
with tf.Session() as sess:
   
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess.run([cost,optimizer],feed_dict={x:inp,y:op})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
    print ("Validating output for EXNOR GATE")
    result=sess.run(z,feed_dict={x:inp})
    print (result)

iteration=  0 cost=  1.12289
iteration=  1000 cost=  0.694588
iteration=  2000 cost=  0.693174
iteration=  3000 cost=  0.693148
iteration=  4000 cost=  0.693147
iteration=  5000 cost=  0.693147
iteration=  6000 cost=  0.693147
iteration=  7000 cost=  0.693147
iteration=  8000 cost=  0.693147
iteration=  9000 cost=  0.693147
iteration=  10000 cost=  0.693147
iteration=  11000 cost=  0.693147
iteration=  12000 cost=  0.693147
Validating output for EXNOR GATE
[[ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]]
